In [5]:
import numpy as np

#skalar
scalar = np.array(5)
print(scalar)

#vekotr
vektor = np.array([1,2,3])
print(vektor)

#vektor kolom
kolom = np.array([[1],[2],[3]])
print(kolom)

#2 dimensi
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

#3 dimensi
trx = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(trx)

#baris kolom
elemen = trx[2,2]
print(elemen)

# akses 1 baris 
elemen = trx[1,:]
print(elemen)

# akses 1 kolom 
elemen = trx[:,2]
print(elemen)

#
elemen = trx[0:2,1:3]
print(elemen)

5
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
90
[40 50 60]
[30 60 90]
[[20 30]
 [50 60]]


In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

perkalian = np.dot(A,B)
print(f"Perkalian: \n{perkalian}")

invers = np.linalg.inv(A)
print(f"Invers: \n{invers}")

determinan = np.linalg.det(B)
print(f"Determinan: \n{determinan}")

NameError: name 'np' is not defined

# Sistem Linear

In [ ]:
# 2x + y = 22
# x + y = 12
# x = 10 y = 2
ruas_kiri = np.array([
    [2,1], # persamaan 1 (x = 2, y = 1)
    [1,1] # persamaan 2 (x = 1, y = 1)
])

ruas_kanan = np.array([
    22, # jawban pers 1
    12  # jawban pers 2
])

jawaban = np.linalg.solve(ruas_kiri,ruas_kanan)
print(jawaban)

# Penggabunga Matrix

In [16]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

#Horizontal  
gabungan = np.hstack((A,B))
print(gabungan)

#Vertikal
gabungan = np.vstack((A,B))
print(gabungan)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Pembentukan Matrix

In [24]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([1,2,3,4])

#RESHAPE
print(f"Sebleum di reshape {B}")
print(f"Sesudah di reshape:\n {B.reshape(2,2)}")

#FLATTEN
print(f"Sebleum di Flatten {A}")
print(f"Sesudah di Flatten:\n {A.flatten()}")

#RESIZE
print(f"Sebleum di Resize: \n{B}")
print(f"Sesudah di Resize: \n{np.resize(B,(2,3))}")

Sebleum di reshape [1 2 3 4]
Sesudah di reshape:
 [[1 2]
 [3 4]]
Sebleum di Flatten [[1 2]
 [3 4]]
Sesudah di Flatten:
 [1 2 3 4]
Sebleum di Resize: 
[1 2 3 4]
Sesudah di Resize: 
[[1 2 3]
 [4 1 2]]
